<?php
/******************************************* Initialise/Declare variables *****************************************************/
global $displayMessage;
global $pageLimit;
global $company;
global $address;
global $telephone;
global $fax;
global $email;
global $website;
global $organizationHead;
global $designation;
global $mobile;
global $employeeCount;
global $chkShipOwners;
global $chkShippingAgnts;
global $chkFreight;
global $chkAirlines;
global $chkAirCargo;
global $chkAirCraft;
global $chkShipbuilders;
global $chkShipCharters;
global $chkEnginBuilders;
global $chkShipBrokers;
global $chkBunkers;
global $chkShipChandler;
global $chkStevedores;
global $chkWarehousing;
global $chkMarineContainer;
global $chkMaritime;
global $chkContainerTrucking;
global $chkEquipmentOwners;
global $chkCourier;
global $chkLashing;
global $chkLogistics;
global $chkPacking;
global $chkPestControl;
global $chkProjectCargo;
global $chkSupplyChain;
global $chkConsultants;
global $chkShipManagers;
global $chkMaritimeSchool;
global $chkMarineInsurance;
global $chkMaritimeLawyers;
global $chkClassification;
global $chkTowage;
global $chkOffshore;

$displayMessage = "";
$company = "";
$address = "";
$telephone = "";
$fax = "";
$email = "";
$website = "";
$organizationHead = "";
$designation = "";
$mobile = "";
$employeeCount = "";
$chkShipOwners = "";
$chkShippingAgnts = "";
$chkFreight = "";
$chkAirlines = "";
$chkAirCargo = "";
$chkAirCraft = "";
$chkShipbuilders = "";
$chkShipCharters = "";
$chkEnginBuilders = "";
$chkShipBrokers = "";
$chkBunkers = "";
$chkShipChandler = "";
$chkStevedores = "";
$chkWarehousing = "";
$chkMarineContainer = "";
$chkMaritime = "";
$chkContainerTrucking = "";
$chkEquipmentOwners = "";
$chkCourier = "";
$chkLashing = "";
$chkLogistics = "";
$chkPacking = "";
$chkPestControl = "";
$chkProjectCargo = "";
$chkSupplyChain = "";
$chkConsultants = "";
$chkShipManagers = "";
$chkMaritimeSchool = "";
$chkMarineInsurance = "";
$chkMaritimeLawyers = "";
$chkClassification = "";
$chkTowage = "";
$chkOffshore = "";																																										
/******************************************* Control flow starts **************************************************************/
if(isset($_REQUEST['btnActivate'])){
	getValuesFromForm();
	$activate=activateFreelist($listId);
	if($activate==1) $displayMessage="Freelist has been activated";
	else $displayMessage="Unable to activate Freelist. Please try again later";
	$freelistDetails=getFreeListDetails($listId);
	assignDBValuesToForm($freelistDetails);
	setValuesToForm();
	$branchList=getFreelistBranches($listId);
	$footerLeft=formatDisplayText(getFooter('left'));
	$footerRight=formatDisplayText(getFooter('right'));	
}else{
	getValuesFromForm();
	$freelistDetails=getFreeListDetails($listId);
	assignDBValuesToForm($freelistDetails);
	setValuesToForm();
	$branchList=getFreelistBranches($listId);
	$footerLeft=formatDisplayText(getFooter('left'));
	$footerRight=formatDisplayText(getFooter('right'));
}

/******************************************* Control flow ends ****************************************************************/
/******************************************* Page level functions starts *****************************************************/
function getValuesFromForm(){
	global $listId;
	
	$listId=isset($_REQUEST['editId'])?$_REQUEST['editId']:0;
} 
function assignDBValuesToForm($rsResult){
	global $db;
	global $company;
	global $address;
	global $telephone;
	global $fax;
	global $email;
	global $website;
	global $organizationHead;
	global $designation;
	global $mobile;
	global $employeeCount;
	global $chkShipOwners;
	global $chkShippingAgnts;
	global $chkFreight;
	global $chkAirlines;
	global $chkAirCargo;
	global $chkAirCraft;
	global $chkShipbuilders;
	global $chkEnginBuilders;
	global $chkShipCharters;
	global $chkShipBrokers;
	global $chkBunkers;
	global $chkShipChandler;
	global $chkStevedores;
	global $chkWarehousing;
	global $chkMarineContainer;
	global $chkMaritime;
	global $chkContainerTrucking;
	global $chkEquipmentOwners;
	global $chkCourier;
	global $chkLashing;
	global $chkLogistics;
	global $chkPacking;
	global $chkPestControl;
	global $chkProjectCargo;
	global $chkSupplyChain;
	global $chkConsultants;
	global $chkShipManagers;
	global $chkMaritimeSchool;
	global $chkMarineInsurance;
	global $chkMaritimeLawyers;
	global $chkClassification;
	global $chkTowage;
	global $chkOffshore;
	
	$details=$db->sql_fetchrow($rsResult);
	$company=$details['companyName'];
	$address=$details['address'];
	$telephone=$details['telephone'];
	$fax=$details['fax'];
	$email=$details['email'];
	$website=$details['website'];
	$organizationHead=$details['organizationHead'];
	$designation=$details['designation'];
	$mobile=$details['mobile'];
	$employeeCount=$details['employeeCount'];
	$chkShipOwners=$details['shipOwners'];
	$chkShippingAgnts=$details['shippingAgents'];
	$chkFreight=$details['freightForwarding'];
	$chkAirlines=$details['airlines'];
	$chkAirCargo=$details['airCargoAgents'];
	$chkAirCraft=$details['airCraft'];
	$chkShipbuilders=$details['shipBuilders'];
	$chkEnginBuilders=$details['engineBuilders'];
	$chkShipCharters=$details['shipCharters'];
	$chkShipBrokers=$details['shipBrokers'];
	$chkBunkers=$details['bunkers'];
	$chkShipChandler=$details['shipChandler'];
	$chkStevedores=$details['stevedores'];
	$chkWarehousing=$details['wareHouse'];
	$chkMarineContainer=$details['marineContainer'];
	$chkMaritime=$details['maritimeOrganisations'];
	$chkContainerTrucking=$details['containerTrucking'];
	$chkEquipmentOwners=$details['equipmentOwners'];
	$chkCourier=$details['courierServices'];
	$chkLashing=$details['lashSecure'];
	$chkLogistics=$details['logistics'];
	$chkPacking=$details['packingRemovals'];
	$chkPestControl=$details['pestControl'];
	$chkProjectCargo=$details['projectCargo'];
	$chkSupplyChain=$details['supplyChain'];
	$chkConsultants=$details['consultants'];
	$chkShipManagers=$details['shipManagers'];
	$chkMaritimeSchool=$details['maritimeSchools'];
	$chkMarineInsurance=$details['marineInsurance'];
	$chkMaritimeLawyers=$details['maritimeLawyers'];
	$chkClassification=$details['classificationSocieties'];
	$chkTowage=$details['towage'];
	$chkOffshore=$details['offshoreOnshore'];
}
function setValuesToForm(){
	global $company;
	global $address;
	global $telephone;
	global $fax;
	global $email;
	global $website;
	global $organizationHead;
	global $designation;
	global $mobile;
	global $employeeCount;
	global $chkShipOwners;
	global $chkShippingAgnts;
	global $chkFreight;
	global $chkAirlines;
	global $chkAirCargo;
	global $chkAirCraft;
	global $chkShipbuilders;
	global $chkShipCharters;
	global $chkEnginBuilders;
	global $chkShipBrokers;
	global $chkBunkers;
	global $chkShipChandler;
	global $chkStevedores;
	global $chkWarehousing;
	global $chkMarineContainer;
	global $chkMaritime;
	global $chkContainerTrucking;
	global $chkEquipmentOwners;
	global $chkCourier;
	global $chkLashing;
	global $chkLogistics;
	global $chkPacking;
	global $chkPestControl;
	global $chkProjectCargo;
	global $chkSupplyChain;
	global $chkConsultants;
	global $chkShipManagers;
	global $chkMaritimeSchool;
	global $chkMarineInsurance;
	global $chkMaritimeLawyers;
	global $chkClassification;
	global $chkTowage;
	global $chkOffshore;

	$company=formatDisplayText($company);
	$address=formatDisplayText($address);
	$fax=formatDisplayText($fax);
	$telephone=formatDisplayText($telephone);
	$email=formatDisplayText($email);
	$website=formatDisplayText($website);
	$organizationHead=formatDisplayText($organizationHead);
	$designation=formatDisplayText($designation);
	$mobile=formatDisplayText($mobile);
	$employeeCount=formatDisplayText($employeeCount);
	$chkShippingAgnts=formatDisplayText($chkShippingAgnts);
	$chkShipOwners=formatDisplayText($chkShipOwners);
	$chkFreight=formatDisplayText($chkFreight);
	$chkAirlines=formatDisplayText($chkAirlines);
	$chkAirCargo=formatDisplayText($chkAirCargo);
	$chkAirCraft=formatDisplayText($chkAirCraft);
	$chkShipbuilders=formatDisplayText($chkShipbuilders);
	$chkShipCharters=formatDisplayText($chkShipCharters);
	$chkEnginBuilders=formatDisplayText($chkEnginBuilders);
	$chkShipBrokers=formatDisplayText($chkShipBrokers);
	$chkBunkers=formatDisplayText($chkBunkers);
	$chkShipChandler=formatDisplayText($chkShipChandler);
	$chkStevedores=formatDisplayText($chkStevedores);
	$chkWarehousing=formatDisplayText($chkWarehousing);
	$chkMarineContainer=formatDisplayText($chkMarineContainer);
	$chkMaritime=formatDisplayText($chkMaritime);
	$chkContainerTrucking=formatDisplayText($chkContainerTrucking);
	$chkEquipmentOwners=formatDisplayText($chkEquipmentOwners);
	$chkCourier=formatDisplayText($chkCourier);
	$chkLashing=formatDisplayText($chkLashing);
	$chkLogistics=formatDisplayText($chkLogistics);
	$chkPacking=formatDisplayText($chkPacking);
	$chkPestControl=formatDisplayText($chkPestControl);
	$chkProjectCargo=formatDisplayText($chkProjectCargo);
	$chkSupplyChain=formatDisplayText($chkSupplyChain);
	$chkConsultants=formatDisplayText($chkConsultants);
	$chkShipManagers=formatDisplayText($chkShipManagers);
	$chkMaritimeSchool=formatDisplayText($chkMaritimeSchool);
	$chkMarineInsurance=formatDisplayText($chkMarineInsurance);
	$chkMaritimeLawyers=formatDisplayText($chkMaritimeLawyers);
	$chkClassification=formatDisplayText($chkClassification);
	$chkTowage=formatDisplayText($chkTowage);
	$chkOffshore=formatDisplayText($chkOffshore);
}
/******************************************* Page level functions ends *******************************************************/
?>